### ISSUE TITLE
White/blank screen when starting the application.

### ISSUE THREAD

**Issue by parrel** [xJoeyv/My-Electron#1]
Hello Joey,

When I open the app with `npm start`, a white blank window shows up. What I did:

1. Download and extract the ZIP
2. Open a terminal in the folder where it was extracted
3. Run `npm i`
4. Run `npm start`

There were no errors in the process described above. When I run `npm start`, the following is logged in the console:

>$ npm start
>
> \> app-name@1.0.0 start C:\PathHere\My-Electron-master
> \> electron .

Thanks!

**Comment by xJoeyv** [comment]
I used the release version and did the setup successfull on my current machine. Please follow the steps given below.

**Steps**
1. Update Node ( 8.7.0=> ) 
2. Update Npm ( 5.4.2=> )
3. Download a Release ( https://github.com/xJoeyv/My-Electron/archive/1.1.zip )
4. Run ```npm i``` in the root folder of My Electron
5. Run ```npm start``` in the root folder of My Electron

**Comment by parrel** [comment]
Hello,
I updated Node:
> $ node -v
> v8.9.4

I updated NPM
> $ npm -v
> 5.6.0

I re-downloaded your release and extracted it again. I ran the two npm commands and the HTML still does not load for some reason. This is where I'm looking at right now:
![image](https://user-images.githubusercontent.com/22742147/34947366-252a0a7c-fa0a-11e7-8238-6a526ffa8fc8.png)

**Comment by parrel** [comment]
Okay so I found a fix while searching on the internet. When turning off hardware acceleration in your app, it worked. I added the following to main.js: `app.disableHardwareAcceleration();`.

Seems to be a GPU or driver issue on my end.

Anyway, I'll close this issue now.
